# Generated by Django 2.2.21 on 2021-06-15 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appuntamenti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.TimeField()),
            ],
            options={
                'verbose_name': 'Appuntamento',
                'verbose_name_plural': 'Appuntamenti',
            },
        ),
        migrations.CreateModel(
            name='Clienti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cognome', models.CharField(max_length=30)),
                ('Nome', models.CharField(max_length=30)),
                ('Sesso', models.CharField(choices=[('F', 'Femmina'), ('M', 'Maschio'), ('U', 'Non sicuro')], max_length=1)),
                ('DataNascita', models.DateField()),
                ('Indirizzo', models.CharField(max_length=50)),
                ('RecapitoTelefonico', models.CharField(max_length=11)),
                ('Email', models.EmailField(max_length=254)),
                ('DocumentoIdentitá', models.CharField(max_length=9)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
            },
        ),
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Percentuale', models.CharField(choices=[('22%', '22 Percento')], max_length=3)),
            ],
            options={
                'verbose_name': 'Iva',
                'verbose_name_plural': 'Iva',
            },
        ),
        migrations.CreateModel(
            name='Saloni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeSalone', models.CharField(max_length=30)),
                ('Indirizzo', models.CharField(max_length=50)),
                ('Cittá', models.CharField(max_length=40)),
                ('Descrizione', models.CharField(max_length=40)),
                ('Immagine', models.ImageField(upload_to='')),
                ('RecapitoTelefonico', models.CharField(max_length=11)),
                ('OrarioAperturaMattino', models.CharField(choices=[('07:00', '07:00'), ('07:30', '07:30'), ('08:00', '08:00'), ('08:30', '08:30'), ('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30')], max_length=5)),
                ('OrarioChiusurMattino', models.CharField(choices=[('07:00', '07:00'), ('07:30', '07:30'), ('08:00', '08:00'), ('08:30', '08:30'), ('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30')], max_length=5)),
                ('OrarioAperturaPomeriggio', models.CharField(choices=[('13:30', '13:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30')], max_length=5)),
                ('OrarioChiusuraPomeriggio', models.CharField(choices=[('13:30', '13:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30')], max_length=5)),
            ],
            options={
                'verbose_name': 'Salone',
                'verbose_name_plural': 'Saloni',
            },
        ),
        migrations.CreateModel(
            name='Trattamenti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoTrattamento', models.CharField(max_length=40)),
                ('CostoEsentasse', models.PositiveIntegerField()),
                ('Descrizione', models.TextField(max_length=200)),
                ('IdIva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Iva')),
            ],
            options={
                'verbose_name': 'Trattamento',
                'verbose_name_plural': 'Trattamenti',
            },
        ),
        migrations.CreateModel(
            name='FeedbackCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stelle', models.CharField(choices=[('1', '1 Stella'), ('2', '2 Stelle'), ('3', '3 Stelle'), ('4', '4 Stelle'), ('5', '5 Stelle')], max_length=8)),
                ('Id_Appuntamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Appuntamenti')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Dipendenti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cognome', models.CharField(max_length=30)),
                ('Nome', models.CharField(max_length=30)),
                ('Sesso', models.CharField(choices=[('F', 'Femmina'), ('M', 'Maschio'), ('U', 'Non sicuro')], max_length=1)),
                ('DataNascita', models.DateField()),
                ('Indirizzo', models.CharField(max_length=50)),
                ('RecapitoTelefonico', models.CharField(max_length=11)),
                ('Email', models.EmailField(max_length=254)),
                ('DocumentoIdentitá', models.CharField(max_length=9)),
                ('Salone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Saloni')),
            ],
            options={
                'verbose_name': 'Dipendente',
                'verbose_name_plural': 'Dipendenti',
            },
        ),
        migrations.AddField(
            model_name='appuntamenti',
            name='Id_Dipendente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Dipendenti'),
        ),
        migrations.AddField(
            model_name='appuntamenti',
            name='Id_Salone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Saloni'),
        ),
        migrations.AddField(
            model_name='appuntamenti',
            name='Id_Trattamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Trattamenti'),
        ),
    ]
