# Generated by Django 2.2.21 on 2021-06-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210615_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saloni',
            name='Descrizione',
            field=models.CharField(max_length=200),
        ),
    ]
