# Generated by Django 2.2.21 on 2021-07-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210705_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuntamenti',
            name='Data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appuntamenti',
            name='Ora',
            field=models.TimeField(),
        ),
    ]
